-- No-op migration.
-- The content_flagged columns and foreign key were already added by
-- 20260303000000_add_course_content_flagged, so this later migration must not
-- re-apply the same schema changes during a full reset.
